### ISSUE TITLE
pdf reader can't open created pdf file

### ISSUE THREAD

**Issue by JimmyO-GH** [michaelrsweet/pdfio#19]
after run testpdfio it create a sample pdf file named testpdfio-out.pdf.
this file can't open with acrobat reader.

use current nightly source code.
build it with visual studio
run testpdfio executable.
this create the testpdfio-out.pdf
open this file with pdf reader.

 - OS: Windows 10
 - Visual Studion 2019  v16.9.6
 - Adode Acrobat Read v2020.013.20074
 - Chrome Browser

**Comment by JimmyO-GH** [comment]
after some more test, i see, that follow variables are not correct exported
const double	pdfioAdobeRGBGamma = 2.2;
const double	pdfioAdobeRGBMatrix[3][3] = { { 0.57667, 0.18556, 0.18823 }, { 0.29734, 0.62736, 0.07529 }, { 0.02703, 0.07069, 0.99134 } };
const double	pdfioAdobeRGBWhitePoint[3] = { 0.9505, 1.0, 1.0890 };

so 
  if ((cs = pdfioArrayCreateColorFromMatrix(pdf, 3, pdfioAdobeRGBGamma, pdfioAdobeRGBMatrix, pdfioAdobeRGBWhitePoint)) != NULL)
has some troubles.
i will search for more trouble detail

**Comment by michaelrsweet** [comment]
@JimmyO-GH Please attach the testpdfio-out.pdf file you got.

**Comment by JimmyO-GH** [comment]
hi,
i think MS has change something 
https://docs.microsoft.com/en-us/cpp/build/importing-and-exporting?view=msvc-160
i will make more test with this changes.

**Comment by michaelrsweet** [comment]
@JimmyO-GH I'm using an exports (pdfio1.def) file to avoid any issues with source annotations, and AFAIK MS hasn't changed anything in this tool path in a very long time.

Again, if you can attach the problematic PDF file I will take a look.

**Comment by michaelrsweet** [comment]
I've been able to reproduce it, and it seems like Visual Studio isn't exporting the right values. I might just add a separate API for the standard color spaces to avoid this exports issue... :/

**Comment by michaelrsweet** [comment]
I've replaced the global constants with a separate API (`pdfioArrayCreateColorFromStandard`) to avoid the exports issues...
