### ISSUE TITLE
make all-shared Makefile errors

### ISSUE THREAD

**Issue by zacii7** [michaelrsweet/pdfio#22]
when running `make all-shared`, make fails with several errors

- lines 72,112: `else` is missing trailing backslash

- line 128: `soname` should be `-soname`

- making a shared object requires `-fPIC`

Thanks for the project, it has been extremely useful.

**Comment by zacii7** [comment]
Confirmed this is now working for me

**Comment by michaelrsweet** [comment]
[master f3689d6] Fix all-shared on Linux (Issue #22)
