### ISSUE TITLE
Use floating-point arguments in pdfioContentSetDashPattern

### ISSUE THREAD

**Issue by zacii7** [michaelrsweet/pdfio#25]
In the function `bool pdfioContentSetDashPattern(pdfio_stream_t *st, int phase, int on, int off);`,

There is no reason to restrict the `phase`, `on` and `off` parameters to `int`;
all 3 parameters should accept `double` as input

**Comment by michaelrsweet** [comment]
[master 22c245f] Update pdfioContentSetDashPattern to accept doubles (Issue #25)
