### ISSUE TITLE
API call to get the keys from a dict object?

### ISSUE THREAD

**Issue by JayHiserote** [michaelrsweet/pdfio#31]
Hey Micheal,
I've had some success using experimenting with you code package. I might be missing something but I can't seem to find an api call to return a list of keys from a dict object. What am I missing?
Thanks
-- Jay

**Comment by michaelrsweet** [comment]
@JayHiserote Nope, but I can add one... :)

**Comment by JayHiserote** [comment]
Nice. I’ll verify it.

**Comment by michaelrsweet** [comment]
[master f4b8983] Implement pdfioDictIterateKeys API (Issue #31)
