### ISSUE TITLE
Cant get info from PDF

### ISSUE THREAD

**Issue by ire4ever1190** [michaelrsweet/pdfio#33]
Can't get info (e.g. author, subject, keywords) from PDF when reading in from a file

**To Reproduce**
Compile and run this 
```c
#include "pdfio.h"

int main() {
  { // Create the test file
    pdfio_file_t *pdf = pdfioFileCreate("test.pdf", "2.0", NULL, NULL, NULL, NULL);
    pdfioFileSetAuthor(pdf, "John Doe");
    printf("%s\n", pdfioFileGetAuthor(pdf));
    pdfioFileClose(pdf);
  }
  { // Read it back in
    pdfio_file_t *pdf = pdfioFileOpen("test.pdf", NULL, NULL, NULL, NULL);
    printf("%s", pdfioFileGetAuthor(pdf));
    pdfioFileClose(pdf);
  }
}
```

**Expected behavior**
File should be read back in correctly and print "John Doe" twice

**Additional Info**
I can find `/Author(John Doe)` in the info object so it does seem to be writing correctly

**System Information:**
 - OS: Linux 
 - Version: Latest commit ([26d485c](https://github.com/michaelrsweet/pdfio/commit/26d485cfc51e9a4eea6a687dba46e6a16a0dc20f))

**Comment by michaelrsweet** [comment]
OK, I'm able to reproduce...
