### ISSUE TITLE
Can't create image object from an image file using the supplied fonction

### ISSUE THREAD

**Issue by HABILAReda** [michaelrsweet/pdfio#35]
Hi, 
i am using this library to build a small application that allows me to edit an existing pdf file, for that i opened said pdf file and wanted to insert an image in page indexed at 0.
When i use the function  pdfioFileCreateImageObjFromFile and assign the result to a pdf_obj_t pointer in order to add it to the pages dictionnary, but when i check for the image pointer's value it's NULL i don't know why it's not working.
Please Help!

here's my code:
you might find some libraries that i included in the code but without using any of there functionalities it's because this is still a test version

here's my code:

`#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <pdfio.h>
#include <string.h>
#include <pdfio-content.h>
#define _BUFF_LENGTH 256

bool dict_callback(pdfio_dict_t* dict, const char* key, void* cb_data)
{
    printf("Catalogue has Key: %s\n", key);
    return true;
}
int main()
{
    pdfio_file_t *norme=NULL;

    if((norme=pdfioFileOpen("Fichier Brut.pdf", NULL, NULL, NULL, NULL)))
    {
        pdfio_obj_t *first_page=pdfioFileGetPage(norme, 0),
                    *header_img=pdfioFileCreateImageObjFromFile(norme, "entete.jpg", true);
        if (header_img ==  NULL)
            printf("image file not loaded\n");
        pdfio_dict_t *fpage_dict = pdfioObjGetDict(first_page);
        bool is_added_dict=pdfioPageDictAddImage(fpage_dict, "entete", header_img),
             is_drawn=pdfioContentDrawImage(pdfioPageOpenStream(first_page, 0, false), "\en_tete", 15, 15, pdfioImageGetWidth(header_img),
                              pdfioImageGetHeight(header_img));
        if(is_added_dict && is_drawn)
            printf("Iamge added to dictionnary and drawn\n");
        else if (is_added_dict)
            printf("Image added to dictionnary\n");
        else if (is_drawn)
            printf("Image Drawn\n");
        else
            printf("is added to dictionnary %d \n is drawn %d\n", is_added_dict, is_drawn);

        if (header_img != NULL)
            printf("Image is loaded\n");
        if (first_page != NULL)
            printf("First Page loaded\n");

        printf("Image Object Size: %d\n", pdfioObjGetLength(header_img));

        pdfioFileClose(norme);
        return EXIT_SUCCESS;
    }
    else
        return EXIT_FAILURE;
}
`

as i said erlier when i check for the image objects pointer value with an if instruction i get message "image not loaded" indicating that the value of the pointer is NULL !

**Comment by michaelrsweet** [comment]
Perhaps I need to make this more clear, but PDFio currently does not support modifying an existing PDF file in-place. Instead, you need to create a new PDF and copy pages and/or objects from the existing PDF file.

**Comment by HABILAReda** [comment]
Hello again,

First of all thank you for the quick answer, in fact i did not know that was the case, u really helped me save a lot of unnecessary debug time. 
I have another question if you have the time, using pdfio how can i select text objects from the structure tree root of the pdf or another structure (i am not an expert when it comes to the pdf format i am currenty using the pdf 32000-1 as a refrence manual) in order to add them to a second pdf file or do some further processing to said objects.

Thanks in advance !

**Comment by michaelrsweet** [comment]
OK, so WRT selecting/extracting text objects, that's really a hard problem in general because PDF text is not always in a form that is easily consumable. One method is to scan the page streams for text operators, and the [pdfiototext.c](https://github.com/michaelrsweet/pdfio/blob/master/pdfiototext.c) sample code is a place to start.

**Comment by HABILAReda** [comment]
I see thanks for the heads up i'll see what i can do ones i start taklling that issue.

one last thing this will be my last question, i am currently trying to insert an image file in newly created pdf using the library that you generously shared.
here is my code 

`    
pdfio_file_t *norme=NULL;

    pdfio_rect_t media_box = { 0.0, 0.0, 900.0, 900.0 };  // US Letter
    pdfio_rect_t crop_box = { 36.0, 36.0, 864.0, 864.0 }; // w/0.5" margins
    pdfio_file_t *pdf = pdfioFileCreate("myoutputfile.pdf", "2.0", &media_box, &crop_box, NULL, NULL);
    pdfio_dict_t *page_dict = pdfioDictCreate(pdf);
    pdfio_obj_t *head = pdfioFileCreateImageObjFromFile(pdf, "entete.jpg", true);
    pdfio_stream_t *page_stream=pdfioFileCreatePage(pdf, page_dict);
    bool added=pdfioPageDictAddImage(page_dict, "entete", head);
    bool drawn=pdfioContentDrawImage(page_stream, "entete", 50,50, 200, 100);

    printf("is in dict %d\n", added);
    printf("is drawn %d\n", drawn);
    printf("Image width %lf \nImage Height %lf\n",
           pdfioImageGetWidth(head), pdfioImageGetHeight(head));

    pdfioFileClose(pdf);
`
all the code above is located in the main function of the console program, i did not include the fucntions and includes for extra readability, none the less when i execute the program in fact the pdf is created and when i open it in a hex editor i can see that the image is in fact loded (as a page content stream) but when i open said pdf i get a blank page !

i do not know what i am doing wrong, sorry for the headache and thanks in advance mister.

**Comment by michaelrsweet** [comment]
OK, so a few problems. First, you need to add the image to the page dictionary before you call `pdfioFileCreatePage`, and then you need to call `pdfioStreamClose(page_stream)` after you draw the image to close the page stream.

**Comment by HABILAReda** [comment]
Ok so let me get this stright, what you just told me is the procedure to follow when i wanna add content to a page using pdfio of course, 
Rule 1 Add objects to dictionnary before page creation
Rule 2 Closing the stream at the end of the draw procedure / writting procedure in order to save the progress

thanks a lot for your assistence and have a great day !
