### ISSUE TITLE
Can't add text using supplied functions to a new created pdf file using PDFio

### ISSUE THREAD

**Issue by HABILAReda** [michaelrsweet/pdfio#36]
Hi, so what i wanna do is basically copy pages from an already existing pdf file to a new one, the function that i am using is pdfioPageCopy(), my first issue arrises when i try and copy all pages in the source pdf file to new one generated using pdfioFileCreate(...), my code looks something like this:

```c
#include <pdfio.h>

// declaration of necessary ressources
for (size_t i =0; i<pdfioFileGetNumPages(src_file); i++)
{
     pdfio_obj_t  *page=pdfioFileGetPage(src_file, i);
     pdfioPageCopy(dest_file, page);
}
```

the issue is when i open the phisically creatted file only the first page is coppied properly all the rest look like really small white squares i really do not know why ! i tried calling the pdfioPageCopy() fucntions twice manually without the need of a loop and changing the page index and i got the same results only the first page seems to copy and the other is just a really small white empty square.

my second issue is when i take the first page the one that was copied properly from the destination file and try to add text to it here is the code i used u will [notice that i called pdfioPageCopy() once with the second argument i.e index = 0, i tried to copy the whole thing but got the issue i first described]:

```c
int main()
{
    pdfio_rect_t media_box = {0, 0, _PAGE_WIDTH, _PAGE_HEIGTH},
                 crop_box = {_MARGINS, _MARGINS, _PAGE_WIDTH-_MARGINS, _PAGE_HEIGTH-_MARGINS};
    pdfio_file_t *src_file = pdfioFileOpen("Fichier Brut.pdf", NULL, NULL, NULL, NULL),
                 *dest_file = pdfioFileCreate("Fichier_editer.pdf", "1.4", &media_box, &crop_box, NULL, NULL);

    pdfioPageCopy(dest_file, pdfioFileGetPage(src_file, 0));
    pdfio_obj_t *font=pdfioFileCreateFontObjFromFile(dest_file, "Trebuchet_MS.ttf", true),
                *first_page = pdfioFileGetPage(dest_file, 0);
    pdfio_dict_t *dict = pdfioObjGetDict(first_page);
    pdfioPageDictAddFont(dict, FONT_NAME, font);
    pdfio_stream_t *content_stream = pdfioPageOpenStream(first_page, 0, true);

    pdfioContentSetTextFont(content_stream, FONT_NAME, 10.55);
    pdfioContentSetFillColorRGB(content_stream, 255, 0, 0);
    pdfioContentSetTextCharacterSpacing(content_stream, 0);

    pdfioContentTextBegin(content_stream);
        pdfioContentMatrixTranslate(content_stream, 60, 250);
        pdfioContentTextShow(content_stream, true, "Copyright afnor 2022. Tous droits réservés.");
    pdfioContentTextEnd(content_stream);
    pdfioStreamClose(content_stream);
    pdfioFileClose(src_file);
    pdfioFileClose(dest_file);

    return EXIT_SUCCESS;
}
```

the issue here is when i compile and run the cosole program i get the message: "Fichier editer.pdf": can't dtermine stream length.

after some debuging i realised that the message was printed by the function pdfioPageOpenStream(...) but i have no idea why !

i am using this technique for adding text to a pdf because it was described by you the creatore in another issue listed as an enhancement i think !

thanks in advance and have a nice day !

**Comment by michaelrsweet** [comment]
OK, so the `pdfioPageCopy` function makes an exact copy of the source page to the destination PDF file, copying all resources, etc. but does not leave the new page object open for modifications. To do that will require a different API, something that doesn't close the page object so you can make additions to the page dictionary and create additional page streams.

Until PDFio gets that, you can look at the implementation of `pdfioPageCopy` to create your own version that adds the font object to the destination page dictionary and appends your "watermark" text commands to the end of the new destination page's content stream.

One other note - the current text API has known issues rendering Unicode text (#16) due to the vagaries of PDF's limited Unicode support, but since it looks like you are adding French text you can get away with passing "false" for the unicode parameters to `pdfioFileCreateFontObjFromFile` and `pdfioContentTextShow`. PDFio still treats the input text as UTF-8 but it will map the input Unicode to "WinANSI" (basically ISO-8859-1 with some extra accented characters in the C1 block - covers all the western European languages).

**Comment by michaelrsweet** [comment]
Also, if you can provide a copy of the source document I can look into why you are getting errors...

**Comment by HABILAReda** [comment]
Thanks for the quick answer, where can i find the implimentation de the pdfioCopyPage function i mean the source file name under witch it was implemented, also about the source document here is a copy.
[Fichier Brut.pdf](https://github.com/michaelrsweet/pdfio/files/10148664/Fichier.Brut.pdf)

**Comment by michaelrsweet** [comment]
The `pdfioPageCopy` function is [here](https://github.com/michaelrsweet/pdfio/blob/master/pdfio-page.c).

As for the source PDF, it appears to be correctly formatted and doesn't use any weird PDF extensions. I'll do some more testing to see how it behaves with the IPP sample code's "ipptransform" utility, which uses PDFio to support things like N-up.

**Comment by michaelrsweet** [comment]
... and that seems to work just fine, both for N-up and booklet mode...

**Comment by HABILAReda** [comment]
so i dont understand what i am i doing wrong ... for a quick recap of my approach i just used the pdfioPageCopy in a for loop and saved the results in a new file created with pdfioFileCreate.

**Comment by michaelrsweet** [comment]
So `_pdfioFileAddPage` adds a page object to a file, but isn't intended as a public API. Instead, use `pdfioFileCreatePage` to create a page with content. The code [here](https://github.com/istopwg/ippsample/blob/master/tools/ipptransform.c) shows how ipptransform uses PDFio to support N-up, etc.
