### ISSUE TITLE
PDF to Bitmap

### ISSUE THREAD

**Issue by ffreality** [michaelrsweet/pdfio#38]
Is there any way to render pdf pages as bitmap ? I am working on Unreal Engine 5 android pdf reader. I developed one with PDFium but on Android, it works only with 2018 PDFium without crash. So, if it supports pdf to bitmap feature, I can integrate it.

**Comment by michaelrsweet** [comment]
Sorry, PDFio is just for reading and writing PDF files, not for rendering them...
