### ISSUE TITLE
Problem in pdfio related to embedded streams and <CR><LF> as separator.

### ISSUE THREAD

**Issue by AFischer4** [michaelrsweet/pdfio#40]
Hello, 
I’m new to the pdf conversion thing, appreciate your work but ran into problems…
This is what I found out and I attached a diff with my approach to solve the problem.
(I’m not familiar with github and I might have garbled some info trying to edit this. Please read with brain enabled.)

The problem pops up in the external tool `pdftoppm` but it starts in `pdfio`, when the problematic pattern `stream<CR><LF>` in the input PDF is not correctly converted.
The start of the embedded stream points to the `<LF>` instead of the following byte.
Normally whitespace in front of tokens will be removed, but embedded streams are handled differently.

I noticed the problem, when I tried to convert photos and PDFs sent from an Android smartphone (`Producer(Skia/PDF m100)`), which contains `<CR><LF>` as separators instead of the usual `<LF>` only.
This is the error message of `pdftoppm`:
`pdftoppm: Syntax Error (116748): Unknown compression method in flate stream`

(I tried the `poppler` version 0.71 and a self compiled `XPDF`-version 4.04 of `pdftpoppm`, which I compiled natively on a Raspberry Pi4 with Debian 10, and got the same error. Both tools must be patched too, to skip more than one separator after stream.)

Annotated partial Dump of the input PDF:
```
00000000h: 25 50 44 46 2D 31 2E 34 0D 0A 25 A1 B3 C5 D7 0D ; %PDF-1.4..%.
00000010h: 0A 31 20 30 20 6F 62 6A 0D 0A 3C 3C 2F 50 72 6F ; .1 0 obj..<</Pro
00000020h: 64 75 63 65 72 28 53 6B 69 61 2F 50 44 46 20 6D ; ducer(Skia/PDF m
00000030h: 31 30 30 29 3E 3E 0D 0A 65 6E 64 6F 62 6A 0D 0A ; 100)>>..endobj..
<•••>
```
```
00122c51h:    0D 0A                                        ; ..
00122c53h:          3C 3C 2F 46 69 6C 74 65 72 2F 46 6C 61 ;   <</Filter/Fla
00122c60h: 74 65 44 65 63 6F 64 65 2F 4C 65 6E 67 74 68 20 ; teDecode/Length 
00122c70h: 38 32 3E 3E                                     ; 82>>             // <-- Length of the embedded stream
00122c74h:             73 74 72 65 61 73 74 72 65 61 6D 0D ;     stream.       
00122c7bh:                                  0A             ;            .     // <-- <LF> as additional separator. This position is erroneously used as the beginning of the stream.
00122c7ch:                                     78 9C 33 54 ;             x3T  // <-- This is the expected stream contents.
00122c80h: 30 00 42 5D 43 20 61 61 62 A8 90 9C CB 55 C8 05 ; 0.B]C aabU.
00122c90h: 12 31 B5 34 05 0B 14 A5 72 85 6B 29 E4 01 45 8D ; .14...rk).E
00122ca0h: 2D 2C F4 4C 4D 8C 0C 8C 20 3A 40 92 86 06 C6 7A ; -,LM. :@.z
00122cb0h: 46 46 16 96 16 96 30 CD FA EE C6 0A E9 C5 5C FA ; FF..0.\
00122cc0h: 11 26 0A 2E F9 5C 81 40 08 00 A7 DA 13 99       ; .&..\@....        // 4 + 4*16 + 14= 4+64+14= 82 
00122cceh:                                           0D 0A ;               ..  // <CR><LF> does not belong to the previous stream.
00122cd0h: 65 6E 64 73 74 72 65 61 6D 0D 0A                ; endstream..
00122cd0h:                                  65 6E 64 6F 62 ;            endob

```

These are the debug outputs from the pdfio-Library, which are related to the error:
 (I replaced the normally invisible `\015\012` in the debug output with `<CR><LF>`)
  ```
_pdfioObjLoad: Header is '5 0 obj
  <</Filter/FlateDecode/Length 82>>stream<CR><LF>x?3T0'.
  _pdfioFileConsume(pdf=0x556bd21b80, bytes=42)  // I think this consumes <CR><LF><</Filter/FlateDecode/Length 82>>stream<CR>"
                                                 //, but not the additional <LF>
  <....>
  _pdfioTokenFlush: Remainder '\012x?3T0\000B<.....>' // The first byte is <LF>, which should not belong to the embedded stream! 
  _pdfioObjLoad: stream_offset=1191035.               // The file position of the beginning of the embedded stream is off by one. 
  
```

[embedded_stream_with_CR_LF.patch](https://github.com/michaelrsweet/pdfio/files/11348221/embedded_stream_with_CR_LF.patch)

I hope this helps..
Andreas

**Comment by michaelrsweet** [comment]
Please attach a sample PDF that exhibits this issue.

**Comment by AFischer4** [comment]
This is my 3rd trial to send the requested file. (The first two versions contained more information, but they are probable lost. This time only the absolutely necessary…)
[veranst.pdf](https://github.com/michaelrsweet/pdfio/files/11421700/veranst.pdf)

**Comment by michaelrsweet** [comment]
I've incorporated a variation of the fix you posted over in the ippsample project; I'm not sure these PDFs are technically correct but since Microsoft Word is the creator I'm going to bow to the market share and include this compatibility change.

[master a83f7f5] Allow extra whitespace/newlines after stream tokens (Issue #40)
