### ISSUE TITLE
Unsupported compound stream filter.

### ISSUE THREAD

**Issue by kleuter** [michaelrsweet/pdfio#47]
There is a bunch of files that cannot be opened with pdfio.

**System Information:**
 - OS: Windows 10, Visual Studio 2019

[eFFF_BE0445890588_202300011.pdf](https://github.com/michaelrsweet/pdfio/files/12854473/eFFF_BE0445890588_202300011.pdf)

**Comment by kleuter** [comment]
[another_file.pdf](https://github.com/michaelrsweet/pdfio/files/12854469/another_file.pdf)

**Comment by kleuter** [comment]
Duplicate of https://github.com/michaelrsweet/pdfio/issues/11
?

**Comment by michaelrsweet** [comment]
Not a duplicate, a separate issue.

The file uses the compound stream filter construction with a single filter (!) - I can update PDFio to handle this special case but full compound filter support is still a future work item (it isn't commonly used, which is why I haven't bothered yet...)

**Comment by michaelrsweet** [comment]
[master 2e91e05] Allow "compound" filters that consist of a single named filter (Issue #47)
