### ISSUE TITLE
Too many object streams error

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/pdfio#58]
The attached file that was created by merging multiple PDF files yields the "too many object streams" error.
[tillA4-A3-A4-3-pdftopdf.pdf](https://github.com/michaelrsweet/pdfio/files/13639459/tillA4-A3-A4-3-pdftopdf.pdf)

**Comment by michaelrsweet** [comment]
[master 038fd86] Fix trailer dictionary handling (Issue #58) Fix generation number handling for object 0 (Issue #59)

**Comment by akorobkin** [comment]
Thanks, the "Unexpected 'startxref' token seen." is gone now. 

`Too many object streams` error can be seen with this file for example: https://www.etsi.org/deliver/etsi_ts/136500_136599/13652101/16.06.00_60/ts_13652101v160600p.pdf
