### ISSUE TITLE
Malformed xref table entry '0000000000 65536 f'

### ISSUE THREAD

**Issue by akorobkin** [michaelrsweet/pdfio#59]
testpdfio reports `Malformed xref table entry '0000000000 65536 f'` on these attached files. 

[shineline.pdf](https://github.com/michaelrsweet/pdfio/files/13639760/shineline.pdf)
[china-visa-application.pdf](https://github.com/michaelrsweet/pdfio/files/13639761/china-visa-application.pdf)

**Comment by michaelrsweet** [comment]
[master 038fd86] Fix trailer dictionary handling (Issue #58) Fix generation number handling for object 0 (Issue #59)

**Comment by akorobkin** [comment]
Thank you, it works now.
