### ISSUE TITLE
acrobat reader: The font '<font>' contains bad /Widths

### ISSUE THREAD

**Issue by zacii7** [michaelrsweet/pdfio#64]
fonts embedded by `pdfioFileCreateFontObjFromFile` give adobe acrobat reader trouble. all other pdf viewers i have tried work fine.
on PC, it gives an error message: "The font '...' contains bad /Widths". after clicking "ok", the pdf renders, but text alignment is off. on mobile (android; I have not tried others), as well as acrobat online, it does not render any text at all with these fonts. even when searching for text that should be there, nothing comes up. the rest of the pdf is rendered correctly.

I have used the same font with perl PDF::API2, and the text does display correctly on acrobat mobile.

I dont know it this is an issue with pdfio or the ttf library. the problem only comes up when used in a pdf.

**Comment by michaelrsweet** [comment]
Please attach a sample PDF generated with PDFio and the corresponding TTF file. I can't reproduce with the test suite.

**Comment by zacii7** [comment]
here is an example pdf with 2 lines of text. the first line is in a base font. the second line is in a custom font. it displays fine in all viewers except adobe acrobat (android mobile, and online), which displays only the first line.
[sample2.pdf](https://github.com/michaelrsweet/pdfio/files/14521651/sample2.pdf)

here are the fonts i am using, but i have had the same problem with any other fonts i have tried
[fonts.zip](https://github.com/michaelrsweet/pdfio/files/14521666/fonts.zip)

the same fonts work in acrobat when generated with perl PDF::API2
eg. [sample.pdf](https://github.com/michaelrsweet/pdfio/files/14522320/sample.pdf)

on your test output file, i notice the unicode fonts do display in acrobat, but the regular one does not. when I try setting the unicode parameter in both `pdfioFileCreateFontObjFromFile` and `pdfioContentTextShow`, I get strange results in all pdf viewers, including acrobat, where each character is replaced by the preceding one alphabetically, and the character spacing is off. 
eg. [sample3.pdf](https://github.com/michaelrsweet/pdfio/files/14522220/sample3.pdf). this also happens with the OpenSans-Regular.ttf file from the test suite. though in the test suite output file it looks correct.

**Comment by michaelrsweet** [comment]
> should there be any other difference whether or not unicode is set? if I change all unicode parameters to 1, would that have any other effect on the output pdf?

Well it will make the PDF a little larger but otherwise it will work the same. And obviously there must be some issue with the fonts using an 8-bit subset (not all TrueType fonts support non-Unicode usage...)
