### ISSUE TITLE
doc/pdfio.md internal links are broken

### ISSUE THREAD

**Issue by step-** [michaelrsweet/pdfio#65]
**Describe the bug**
Internal links in file doc/pdfio.md are broken. Many of them point to "@" or "@@".

**To Reproduce**
Open <https://github.com/michaelrsweet/pdfio/blob/cd1406e1586feb98adc333e925ddb317cfd42732/doc/pdfio.md> and click some internal links.

**Comment by michaelrsweet** [comment]
This file is input to [codedoc](https://www.msweet.org/codedoc/) - the "@" and "@@" are used to map the link text to the corresponding anchor names.

**Comment by step-** [comment]
I wasn't aware of codedoc so I misinterpreted the purpose of the markdown file. I read the codedoc documentation, and I think I can use it for some of my own projects. Thank you!
