### ISSUE TITLE
Incompatibility with MinGW

### ISSUE THREAD

**Issue by William65536** [michaelrsweet/pdfio#66]
Currently pdfio-private.h contains the following three lines:

https://github.com/michaelrsweet/pdfio/blob/6c1db141a105b76ca1fa1b88175ae6a4e1e8c2ee/pdfio-private.h#L41-L43

which override three of the four definitions in io.h when using [MinGW](https://en.wikipedia.org/wiki/Mingw-w64) on Windows:

```c
#define	F_OK	0	/* Check for file existence */
#define	X_OK	1	/* Check for execute permission. */
#define	W_OK	2	/* Check for write permission */
#define	R_OK	4	/* Check for read permission */
```

The second clause in section 6.10.3 of the _ISO C99 Standard_ mandates that

> An identifier currently defined as an object-like macro shall not be redefined by another
#define preprocessing directive unless the second definition is an object-like macro
definition and the two replacement lists are identical.

and section 6.10.3 clause 1 defines the equality of macro bodies as

>  Two replacement lists are identical if and only if the preprocessing tokens in both have
the same number, ordering, spelling, and white-space separation, where all white-space
separations are considered identical.

Even though `cpp` does not necessarily complain about the above violation of the C standard, other tools such as [Zig](https://ziglang.org/)'s [`translate-c`](https://zig.guide/working-with-c/translate-c/) do, preventing the user from building pdfio without manually editing the lines in pdfio-private.h.

All code of the same form as the definitions in pdfio-private.h should therefore be changed to:

```c
#ifndef F_OK
#define F_OK	00
#endif
#ifndef W_OK
#define W_OK	02
#endif
#ifndef R_OK
#define R_OK	04
#endif
```

to ensure no conflicting definitions.

**Comment by michaelrsweet** [comment]
Scheduling for a future stable release.

Note that I have NOT tested PDFio with MingW or any other alternative toolchain for Windows. These definitions are explicitly in place to support building on Windows using the Visual C compiler. Anything else is *not* supported at this time.

**Comment by michaelrsweet** [comment]
[master f040cc4] Add #define guard to allow MingW to build PDFio; note that MingW is NOT a supported toolchain for PDFio (Issue #66)
