### ISSUE TITLE
Would you be so kind to write a plain simple example of pdf writing?

### ISSUE THREAD

**Issue by raphael10-collab** [michaelrsweet/pdfio#69]
Would you be so kind to write a plain simple example of pdf writing?

For example:

        std::string PdfFileName = "output.pdf";
        std::string completePathToPdfFile = PdfCreatedPath + "/" + PdfFileName;

        pdfio_rect_t media_box = { 0.0, 0.0, 612.0, 792.0 };  // US Letter
        pdfio_rect_t crop_box = { 36.0, 36.0, 576.0, 756.0 }; // w/0.5" margins
        pdfio_output_cb_t output_cb;
        void *output_cbdata;
        pdfio_error_cb_t error_cb;
        void  *error_cb_data;
        pdfio_file_t *pdf = pdfioFileCreateOutput(output_cb, output_cbdata, "2.0", &media_box, &crop_box, error_cb, error_cb_data);

How to set the file path ?

**Comment by michaelrsweet** [comment]
I'll investigate providing some more complete examples using the content APIs.

In the meantime, if you want to write to a named file, use the `pdfioFileCreate` function - `pdfioFileCreateOutput` is intended for streaming PDF output to some destination - it might be a file, or a socket, or an in-memory buffer.

**Comment by raphael10-collab** [comment]
Thank you Michael

**Comment by michaelrsweet** [comment]
Using this issue to track documentation improvements. I'll close when done.

**Comment by raphael10-collab** [comment]
Ok. Thank you @michaelrsweet 

In the meanwhile, I ask you a couple of things I do not understand

With this code : 
    
            pdfio_rect_t media_box = { 0.0, 0.0, 612.0, 792.0 };  // US Letter
            pdfio_rect_t crop_box = { 36.0, 36.0, 576.0, 756.0 }; // w/0.5" margins
            pdfio_output_cb_t output_cb;
            void *output_cbdata;
            pdfio_error_cb_t error_cb;
    
            void  *error_cb_data;
            int outfd;
            bool error = false;
            // https://github.com/michaelrsweet/pdfio/blob/master/pdfio-file.c
            // testpdfio.c
            pdfio_file_t *pdf = pdfioFileCreate(completePathToPdfFile.c_str(), NULL, NULL, NULL, (pdfio_error_cb_t)error_cb, &error);
            pdfio_file_t *inputpdf = pdfioFileOpen("/home/raphy/GraspAppData/PdfCreated/output.pdf", NULL, NULL, (pdfio_error_cb_t)error_cb, &error);
            pdfio_obj_t *img = pdfioFileCreateImageObjFromFile(pdf, "/home/raphy/GraspAppData/PdfCreated/pdfio-color.png", false);
            pdfio_obj_t *courier = pdfioFileCreateFontObjFromBase(pdf, "Courier");
            pdfio_dict_t  *dict = pdfioDictCreate(pdf);
            pdfioPageDictAddFont(dict, "F2", courier);
    
            pdfio_stream_t *st = pdfioFileCreatePage(pdf, dict);
    
            static int num_pages = pdfioFileGetNumPages(pdf);
            std::cout << " static int num_pages = pdfioFileGetNumPages(pdf) : " << num_pages << std::endl;

the output is a PDF file with one empty page:

    static int num_pages = pdfioFileGetNumPages(pdf) : 1

![image](https://github.com/user-attachments/assets/080dba4d-55b7-4652-a218-0a8220b9602b)


In the attempt "to fill" the empty page with some text I added these lines : 

        pdfioContentSetFillColorDeviceGray(st, 0.0);
        pdfioContentTextBegin(st);
        pdfioContentSetTextFont(st, "F1", 18.0);
        pdfioContentTextMoveTo(st, 36.0, 738.0);
        char title[256] = "My First Pdf";
        pdfioContentTextShow(st, true, title);
        pdfioContentSetTextFont(st, "F1", 12.0);
        pdfioContentTextMoveTo(st, 514.0, -702.0);

But the output is the same: one empty page PDF file 

![image](https://github.com/user-attachments/assets/8f3915df-3a92-4846-be5e-bc9f9a989162)

Why?

In the attempt to add an image to the empty page, I added these lines : 

        pdfioDictSetName(dict, "Type", "XObject");
        pdfioDictSetName(dict, "Subtype", "Image");
        pdfioDictSetNumber(dict, "Width", 256);
        pdfioDictSetNumber(dict, "Height", 256);
        pdfioDictSetNumber(dict, "BitsPerComponent", 8);
        pdfioDictSetName(dict, "ColorSpace", "DeviceRGB");
        pdfioDictSetName(dict, "Filter", "FlateDecode");
        pdfio_obj_t *obj = pdfioFileCreateObj(pdf, dict);
        pdfio_dict_t *decode = pdfioDictCreate(pdf);
        pdfioDictSetNumber(decode, "BitsPerComponent", 8);
        pdfioDictSetNumber(decode, "Colors", 3);
        pdfioDictSetNumber(decode, "Columns", 256);

        _pdfio_predictor_t predictor = _PDFIO_PREDICTOR_PNG_AVERAGE;
        pdfioDictSetNumber(decode, "Predictor", predictor);

And got this error : ` error: ‘_pdfio_predictor_t’ was not declared in this scope; did you mean ‘pdfio_rect_t’?` 

In the https://github.com/michaelrsweet/pdfio/blob/master/testpdfio.c the type `_pdfio_predictor_t` , typedef of an enum ( https://github.com/michaelrsweet/pdfio/blob/master/pdfio-private.h#L117 ) is actually used

How to correctly add text and add an image file to the empty page of the created PDF file ?

**Comment by devnibo** [comment]
Hello @raphael10-collab if you're interested I could share a personal project of mine with you in which I use the pdfio library in my C project. I also miss example code how to use the library but some things I did figure out by now.

**Comment by devnibo** [comment]
> I'll investigate providing some more complete examples using the content APIs.

@michaelrsweet if you already have concrete plans of what examples you want to provide, maybe I can write one or two of them. Just so you know I would willing to do so.

**Comment by raphael10-collab** [comment]
@devnibo I actually didn't manage to  even create a simple plain empty pdf page, as you can see here : https://github.com/michaelrsweet/pdfio/issues/69#issuecomment-2225556190

So, any working project examples are welcome

I thank you very much

**Comment by michaelrsweet** [comment]
[master 1d4f77c] Add examples to documentation (Issue #69)
