### ISSUE TITLE
Request for feature of Form Flattness

### ISSUE THREAD

**Issue by uddhavphatak** [michaelrsweet/pdfio#73]
I would like to request the addition of form flattening functionality in the PDF processing pipeline. Form flattening is the process of converting interactive PDF form fields (e.g., text fields, checkboxes, radio buttons) into static, non-editable content. This feature is essential for cases where form fields need to be locked and made uneditable after the form has been filled out.

**Use Case:**
Form flattening would be useful in the following scenarios:

1. Finalizing Forms: After users fill out forms, flattening would ensure that the content becomes static and cannot be modified further.
2. Archiving: Flattening makes the document more secure for archiving and ensures all filled-in data is preserved and non-interactive.
3. Printing: Ensures that interactive elements display properly when printed, as some viewers or printers may not handle form fields correctly.
4. Compatibility: Some PDF viewers may not support interactive forms; flattening them makes the document viewable and consistent across all platforms.

**Comment by michaelrsweet** [comment]
This isn't something that PDFio will be adding - the goal for PDFio is not to render PDF files but to manipulate them. Certainly you could implement a "flattening" functionality with PDFio but doing so requires interpretation of the PDF content streams.
