### ISSUE TITLE
Add pdfioArrayRemove and pdfioDictClear APIs

### ISSUE THREAD

**Issue by uddhavphatak** [michaelrsweet/pdfio#74]
PDFio does not support the dictionary key removal or iteration directly. I have been working around this using the pdfioDictSetNull function, could we add an another function to support dictionary key removal directly

**Comment by michaelrsweet** [comment]
Proposed APIs:

```c
void pdfioArrayRemove(pdfio_array_t *array, size_t n);
void pdfioDictClear(pdfio_dict_t *dict, const char *key);
```

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by uddhavphatak** [comment]
Micheal, I want to try to solve this issue, to solve it, I have a doubt on how to approach this solution. 
I have no idea of how I can do the pdfioArrayRemove, 
but for the pdfioDictClear, I am thinking of making a new PDF file, then going through all the objects, and when the object of the Dict comes, I iterate through the keys of dictionary, and the key which we want to remove, I would skip that key.

is this solution good, or is there any different way I should do it?

**Comment by michaelrsweet** [comment]
@uddhavphatak These functions would only manipulate the array or dictionary in memory, so re-loading the PDF isn’t the approach to take.

**Comment by michaelrsweet** [comment]
[master afac835] Add pdfioDictGetKey and pdfioDictGetNumPairs APIs (Issue #63)
