### ISSUE TITLE
PDF Trailer is not recognized: trailer<<

### ISSUE THREAD

**Issue by vlasovsoft1979** [michaelrsweet/pdfio#80]
**Description**
If there is no space and no new line between "trailer" keyword and "<<" than the trailer is not recognized and we have
"Malformed xref table section 'trailer<<......" error

Is there requirement that the "trailer" keyword should be separated with whitespace or new line?

**How to reproduce**
We have the following PDF trailer:
```
trailer<</Size 46/Info 6 0 R/Root 20 0 R
/Encrypt 7 0 R
/ID[<5dd50a1b97f588ff90b175d49afe402f><5dd50a1b97f588ff90b175d49afe402f>]
>>
```
No new line after the "trailer" keyword. Foxit PDF reader opens this document successfully

**Expected behavior**
Open document successfully

**Comment by vlasovsoft1979** [comment]
I've attached a simple PDF file to demonstrate this problem
[trailer1.pdf](https://github.com/user-attachments/files/17852098/trailer1.pdf)

**Comment by michaelrsweet** [comment]
Thanks, I double-checked the current PDF specification and there isn't a hard requirement to have the keyword "trailer" on a line by itself, so I'll update PDFio to deal with this situation appropriately.

**Comment by michaelrsweet** [comment]
[master d705d7e] Fix reading PDF files whose trailer is missing a newline (Issue #80)
