### ISSUE TITLE
Extend pdfioContentTextMeasure to support the base (PostScript) fonts

### ISSUE THREAD

**Issue by devnibo** [michaelrsweet/pdfio#84]
**Is your feature request related to a problem? Please describe.**
I'm using pdfio for writing an implementation of the [chordpro standard](https://www.chordpro.org/chordpro/). I parse chordpro text and convert it into a pdf file. My program relies heavily on the function `pdfioContentTextMeasure()` to position everything in the pdf. I would like to use the font Helvetica as the default font. I can't do that at the moment because `pdfioContentTextMeasure()` doesn't return the width of text when given a font obtained by `pdfioFileCreateFontObjFromBase()` and I don't have a ttf/otf font file of Helvetica that I could use with the function `pdfioFileCreateFontObjFromFile()`.

**Describe the solution you'd like**
I would like to be able to obtain a base font with `pdfioFileCreateFontObjFromBase()` and then pass the returned `pdfio_obj_t` pointer to `pdfioContentTextMeasure()` which would give me the width of the text instead of returning `0.0`.

**Describe alternatives you've considered**
I thought of switching the pdf library but besides `libharu` which is looking for a maintainer I don't know other good pdf libraries for the C programming language.

**Comment by michaelrsweet** [comment]
Currently PDFio does not contain metrics for the base fonts, so I'll need to convert the metrics I *do* have from HTMLDOC into a form that could be used by PDFio. This is probably doable given the limits of the base fonts (no Unicode support, etc.) so I'll investigate what I'd need to do.

That said, you should really consider embedding a suitable TrueType font, as ISO has deprecated the base fonts and (probably more importantly) the base fonts are not always the same on all platforms, leading to some rendering issues... :/

**Comment by michaelrsweet** [comment]
[master d3d6683] Add support for measuring base fonts (Issue #84)

**Comment by devnibo** [comment]
Wow, thank you!
