### ISSUE TITLE
Font embedding without cutting |字体嵌入未做切割

### ISSUE THREAD

**Issue by YLXDXX** [michaelrsweet/pdfio#85]
**Describe the bug**
When I import a Chinese font using `pdfioFileCreateFontObjFromFile` and then add text using `pdfioContentTextShow(page, true, caption);`, the resulting PDF file becomes very large because the program embeds the entire font file.
Normally, the font is cut to include only the required glyphs.

当我使用 `pdfioFileCreateFontObjFromFile` 引入一个中文字体后，再使用 `pdfioContentTextShow(page, true, caption); ` 添加文字，得到的PDF文件会变得非常大，程序将整个字体文件都嵌入进去了。
正常情况是，会将字体作切割，只包含所需要的那几个字形。

**System Information:**
 - OS: Debian 12
 - Version latest

> Sorry for the poor English, used Google Translate.

**Comment by michaelrsweet** [comment]
The `pdfioFileCreateFontObjFromFile` function does not perform subsetting. Aside from not knowing which characters will be needed from the font, it is only intended as a simple API for embedding whole fonts.

At the moment, I have no plans of adding an API for generating subset or (probably more useful) multiple-master fonts for more complex or better optimized text generation.
